version: '3.8'

services:
  # Frontend - React TypeScript Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    stdin_open: true
    tty: true

  # Backend - Python FastAPI Application  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - MONGODB_URL=mongodb://mongodb:27017/spotify_analyzer
      - CORS_ORIGINS=["http://localhost:3000"]
    depends_on:
      - mongodb
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Database - MongoDB
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-db:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=spotify_analyzer
    
  # Database Admin Interface (optional, for development)
  mongo-express:
    image: mongo-express:1.0.0
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    profiles:
      - debug

volumes:
  mongodb_data:

networks:
  default:
    driver: bridge